Update Build-Apk.yml

diff --git a/.github/workflows/Build-Apk.yml b/.github/workflows/Build-Apk.yml
--- a/.github/workflows/Build-Apk.yml
+++ b/.github/workflows/Build-Apk.yml
@@ -10,6 +10,11 @@ on:
   #     - 'LICENSE'
   #     - '*.md'
   #     - '.github/**'
+env:
+  # Our build metadata
+  # NDK_VERSION: "r28"
+  TAG_NAME: "nightly"
+  VERSION: "1.10.4"
 
 jobs:
   build:
@@ -47,3 +52,45 @@ jobs:
         with:
           name: release
           path: app/build/outputs/apk/gkd/release
+          
+      - name: Get tag version
+        run: |
+          # 如果是手动触发 (workflow_dispatch)
+          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
+            # 获取所有 Tag（确保包含远程 Tag）
+            git fetch --tags
+            # 按版本号排序获取最新 Tag（兼容语义化版本）
+            LATEST_TAG=$(git tag --sort=-v:refname | head -n 1 || echo "nightly")
+
+            # 去掉 Tag 名称中的 'v' 前缀
+            VERSION="${LATEST_TAG}"
+          else
+           # 原有逻辑：从推送的 Tag 中提取版本号
+           TAG_VERSION="${GITHUB_REF##*/}"
+           VERSION="${TAG_VERSION}"
+          fi
+
+          # 处理无 Tag 的情况（可选：报错或默认值）
+          if [ -z "$VERSION" ]; then
+            echo "::error::No valid tag found!"
+            VERSION="0.0.0"
+          fi
+
+          # 将信息写入环境变量
+          echo "TAG_NAME=$LATEST_TAG" >> $GITHUB_ENV
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+
+      - name: Copy sign APK
+        shell: bash
+        run: |
+          mv app/build/outputs/apk/gkd/release/app-gkd-release.apk app/build/outputs/apk/gkd/release/gkd-${{ env.VERSION }}.apk
+
+      - name: Publish signed apk package
+        # if: env.ANDROID_SIGNING_KEY != null && env.UPLOAD_ARTIFACT == 'true'
+        uses: softprops/action-gh-release@v1
+        with:
+          prerelease: true
+          tag_name: ${{ env.TAG_NAME }}
+          files: |
+            app/build/outputs/apk/gkd/release/gkd-${{ env.VERSION }}.apk
+
